src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use App\Repository\UtilisateurRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=UtilisateurRepository::class)
 * @UniqueEntity("username")
 * @UniqueEntity("mail")
 * @UniqueEntity("telephone")
 */
class Utilisateur implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotBlank(message="Metter le nom de l'utilisateur")
     * @ORM\Column(type="string", length=100)
     */
    private $nom;

    /**
     * @Assert\NotBlank(message="Metter le prénom de l'utilisateur")
     * @ORM\Column(type="string", length=100)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $telephone;

    /**
     * @Assert\NotBlank(message="Metter le mot de passe de l'utilisateur")
     * @ORM\Column(type="string", length=100)
     */
    private $password;

    /**
     * @Assert\NotBlank(message="Metter le pseudo de l'utilisateur")
     * @ORM\Column(type="string", length=100, unique=true)
     */
    private $username;

    /**
     * @Assert\NotBlank(message="Metter le mail de l'utilisateur")
     * @ORM\Column(type="string", length=100)
     * @Assert\Email()
     */
    private $mail;

    /**
     * @ORM\Column(type="boolean")
     */
    private $actif;

    /**
     * @Assert\NotBlank(message="Metter le nom du campus l'utilisateur")
     * @ORM\ManyToOne(targetEntity="App\Entity\Campus", inversedBy="utilisateurs")
     * @ORM\JoinColumn(nullable=false)
     */
    private $campus;

    /**
     * @ORM\Column(type="json_array")
     */
    private $roles = [];

    /**
     * @var ArrayCollection
     * @ORM\OneToMany(targetEntity="\App\Entity\Sortie", mappedBy="organisateur",cascade={"persist"}, cascade={"remove"})
     */
    private $sortiesOrganisees;

    /**
     * @var ArrayCollection
     * @ORM\ManyToMany(targetEntity="App\Entity\Sortie", cascade={"persist"}, cascade={"remove"})
     */
    private $sorties;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    public $URLimage;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $resetToken;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $activationToken;


    public function getURLImage(): ?string
    {
        return $this->URLimage;
    }

    public function setURLImage($image): self
    {
        $this->URLimage = $image;

        return $this;
    }

    public function upload()
    {
        // Si jamais il n'y a pas de fichier (champ facultatif), on ne fait rien
        if (null === $this->image) {
            dd("image non trouvee");
            return;
        }
        dd("image trouvee !!!!!!!!!!!!!");
    }






    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function __construct()
    {
        $this->date = new \Datetime();
        $this->Sorties = new ArrayCollection();
    }

    public function addSortie(Sortie $Sortie)
    {
        $this->Sorties[] = $Sortie;

        return $this;
    }

    public function removeSortie(Sortie $Sortie)
    {
        $this->Sorties->removeElement($Sortie);
    }

    /**
     * @param mixed $mail
     */
    public function setMail($mail): void
    {
        $this->mail = $mail;
    }

    /**
     * @return mixed
     */
    public function getMail()
    {
        return $this->mail;
    }



    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getRoles()
    {
        return $this->roles;
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }


    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    /**
     * @return mixed
     */
    public function getActif()
    {
        return $this->actif;
    }

    /**
     * @param mixed $actif
     */
    public function setActif($actif): void
    {
        $this->actif = $actif;
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    /**
     * @return mixed
     */
    public function getCampus()
    {
        return $this->campus;
    }

    /**
     * @param mixed $campus
     */
    public function setCampus($campus): void
    {
        $this->campus = $campus;
    }

    /**
     * @return ArrayCollection
     */
    public function getSorties(): ArrayCollection
    {
        return $this->sorties;
    }

    /**
     * @param ArrayCollection $sorties
     */
    public function setSorties(ArrayCollection $sorties): void
    {
        $this->sorties = $sorties;
    }

    public function __toString()
    {
        return $this->getNom();
    }

    public function getResetToken(): ?string
    {
        return $this->resetToken;
    }

    public function setResetToken(?string $resetToken): self
    {
        $this->resetToken = $resetToken;

        return $this;
    }

    public function getActivationToken(): ?string
    {
        return $this->activationToken;
    }

    public function setActivationToken(?string $activationToken): self
    {
        $this->activationToken = $activationToken;

        return $this;
    }





}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Campus;
use App\Entity\UploadCsv;
use App\Entity\Utilisateur;
use App\Form\ChangePasswordType;
use App\Form\ContactType;
use App\Form\PasswordType;
use App\Form\RegisterType;
use App\Form\UpdateUserType;
use App\Form\UploadCsvType;
use App\GetCurrentUser\GetCurrentUser;
use App\Repository\CampusRepository;
use App\Repository\UploadCsvRepository;
use App\Repository\UtilisateurRepository;
use Doctrine\DBAL\Driver\Mysqli\MysqliException;
use Doctrine\DBAL\Driver\SQLAnywhere\SQLAnywhereException;
use Doctrine\DBAL\Driver\SQLSrv\SQLSrvException;
use Doctrine\DBAL\SQLParserUtilsException;
use Doctrine\ORM\EntityManagerInterface;
use http\Client\Curl\User;
use League\Csv\Reader;
use phpDocumentor\Reflection\Types\This;
use PhpParser\Node\Scalar\String_;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoder;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Csrf\TokenGenerator\TokenGeneratorInterface;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Faker;
use function Matrix\add;


class UserController extends AbstractController
{
    private $encoder;

    public function __construct(UserPasswordEncoderInterface $encoder)
    {
        $this->encoder = $encoder;
    }

    /**
     * @Route("/user", name="user")
     */
    public function index()
    {
        return $this->render('main/home.html.twig');
    }

    /**
     * @Route("/login", name="login")
     */
    public function login()
    {
        return $this->render('user/login.html.twig');
    }
    /**
     * @Route("/logout", name="logout")
     */
    public function logout()
    {

    }
    /**
     * @Route("/admin/register", name="register")
     */
    public function register(Request $request, EntityManagerInterface $em, UserPasswordEncoderInterface $encoder,
                             UtilisateurRepository $ur, ValidatorInterface $validator, TokenGeneratorInterface $token, \Swift_Mailer $mailer)
    {
        $utilisateur = New Utilisateur();
        $registerForm = $this->createForm(RegisterType::class, $utilisateur);
        $registerForm->handleRequest($request);
        $utilisateur->setRoles(["ROLE_USER"]);
        $utilisateur->setActif(1);
        if($registerForm->isSubmitted() && $registerForm->isValid()){
            $erreurs = $validator->validate($utilisateur);
            if(count($erreurs) > 0){
                $this->addFlash('erreurs', 'le username ou le mail est déja utilisé');
                return $this->redirectToRoute('register');

            }else {

                $hash = $encoder->encodePassword($utilisateur, $utilisateur->getPassword());
                $utilisateur->setPassword($hash);
                $utilisateur->setRoles(['ROLE_NOT_ACTIVATE']);

                $utilisateur->setActivationToken(md5(uniqid()));
                $em->persist($utilisateur);
                $em->flush();
                $token = $utilisateur->getActivationToken();
                $url = $this->generateUrl('activation_compte',['token'=>$token], UrlGeneratorInterface::ABSOLUTE_URL);
                $message = (new \Swift_Message('Activation compte'))
                    ->setFrom('send@hey.com')
                    ->setTo($utilisateur->getMail())
                    ->setBody(
                    // $this->renderView(
                    // 'contact/contact.html.twig',compact('contact')
                        'Lien pour réactiver le mot de passe de l\'adresse '.$url
                    //),'text/html'
                    )
                ;
                $mailer->send($message);
                $this->addFlash('success', 'L\'utilisateur a bien été inscrit');
                return $this->redirectToRoute('home');
            }
        }


        return $this->render('user/register.html.twig',[
            'registerForm'=>$registerForm->createView()
        ]);
    }

    /**
     * @Route("/updateUser", name="update_user")
     */
    public function updateUser(Request $request,EntityManagerInterface $em, UtilisateurRepository $ur, ValidatorInterface $validator)
    {

        $utilisateur = $this->getUser();
        $updateUserForm = $this->createForm(UpdateUserType::class, $utilisateur);

        $updateUserForm->handleRequest($request);
        if($updateUserForm->isSubmitted() && $updateUserForm->isValid()) {
            $erreurs = $validator->validate($utilisateur);
            if(count($erreurs) > 0){
                $this->addFlash('erreurs', 'le username ou le mail est déja utilisé');
                return $this->redirectToRoute('register');

            }else{
                /** @var  $uploadFile */
                $uploadFile = $updateUserForm['image']->getData();

                if (!empty($uploadFile)) {
                    $destination = $this->getParameter('kernel.project_dir') . '/public/uploads/ProfilImage';
                    $addresse = 'uploads/ProfilImage/';
                    $newFilename = $utilisateur->getUsername() . '-photoProfil.' . $uploadFile->guessExtension();
                    $uploadFile->move(
                        $destination,
                        $newFilename
                    );
                    $utilisateur->setURLImage($addresse.$newFilename);
                }
                $em->persist($utilisateur);
                $em->flush();
                $this->addFlash('success', 'Modification reussie');
            }
            return $this->redirectToRoute('update_user');
        }
        return $this->render('user/updateUser.html.twig',[
            'updateUserForm'=>$updateUserForm->createView()
        ]);
    }


    /**
     * @Route("/changePassword", name="change_password")
     */
    public function changePassword( Request $request, UserPasswordEncoderInterface $encoder,  UtilisateurRepository $ur,EntityManagerInterface $em)
    {
        $utilisateur = $this->getUser();
        $newPasswordForm = $this->createForm(ChangePasswordType::class, $utilisateur);



        $passBdd = $utilisateur->getPassword();

        $newPasswordForm->handleRequest($request);
        if($newPasswordForm->isSubmitted() && $newPasswordForm->isValid()) {

            $currentPassword = $_POST['_password'];
            $passEncode = $encoder->encodePassword($utilisateur, $currentPassword);

           if($passEncode===$passBdd){

                $newPassword = $encoder->encodePassword($utilisateur, $utilisateur->getPassword());
                $utilisateur->setPassword($newPassword);

                $em->persist($utilisateur);
                $em->flush();
                echo("<br> mdp change");
                return $this->redirectToRoute('update_user',[
                    'id'=>$utilisateur->getId()
                ]);
           }

            echo("<br>mdp non change");
        }



        return $this->render('user/changePassword.html.twig',[
        'newPasswordForm'=>$newPasswordForm->createView()
        ]);
    }

    /**
     * @Route("/afficherProfil/{id}", name="afficher_profil")
     */
    public function afficherProfil($id ,UtilisateurRepository $ur)
    {
        $user = $ur->findOneBy(array("id" => $id));
        return $this->render('user/afficherProfil.html.twig',[
            'user'=>$user
        ]);
    }

    /**
     * @Route("/admin/uploadCsvFile", name="upload_csv_file")
     */
    public function uploadCsvFile(Request $request, EntityManagerInterface $em, CampusRepository $cr,UserPasswordEncoderInterface $encoder, ValidatorInterface $validator, TokenGeneratorInterface $token, \Swift_Mailer $mailer)
    {
        $filesystem = new Filesystem();

        $uc = new UploadCsv();
        $CSVform = $this->createForm(UploadCsvType::class, $uc);
        $CSVform->handleRequest($request);


        if($CSVform->isSubmitted() && $CSVform->isValid()){
            /** @var $uploadFile */
            $uploadFile = $CSVform['file']->getData();

            if(!empty($uploadFile)){
                $destination = $this->getParameter('kernel.project_dir') . '/public/uploads/csv';
                $originalFileName = pathinfo($uploadFile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = transliterator_transliterate('Any-Latin; Latin-ASCII;[^A-Za-z0-9_] remove; Lower()', $originalFileName);
                $newFilename = $safeFilename .'.'.date("d-m-y"). '.'. 'csv';


                $uploadFile->move(
                    $destination,
                    $newFilename
                );
                $uc->setFile($newFilename);
                $em->persist($uc);
                $em->flush();
                $reader = Reader::createFromPath('uploads/csv/'.$uc->getFile());
                $results = $reader->fetchAssoc();
                $allCampus = $cr->findAll();

                foreach ($results as $row) {
                    //dd($row);
                    $campus = new Campus();
                    //$campus->setNom($row['campus']);
                    $campus = $row['campus'];
                    $campusExist = false;
                    foreach($allCampus as $c){
                        //verification de la validité des infos
                        //dd($campus,$c);
                        if($c->getNom() ==  $campus and
                            $row['prenom'] != '' and
                            $row['nom'] != '' and
                            $row['mail'] != '' and
                            $row['username'] != ''){


                            $campus = $cr->find($c->getId());

                            $userUser = new Utilisateur();

templates/user/afficherProfil.html.twig
{% extends 'base.html.twig' %}

{% block title %}Details utilisateur{% endblock %}

{% block main %}
    <div class="main">
        <h1>Details utilisateur</h1>
        {%  if (app.user.uRLImage)== NULL %}
            <img src="{{ asset('uploads/ProfilImage/default.png') }}" class="pdp">
        {%  else %}
            <img src="{{ asset(user.URLImage) }}" class="pdp">
        {% endif %}
        <h2>{{ user.prenom }} {{ user.nom }}</h2>
        <h3>Dit {{ user.username }}</h3>
        <p>Campus : {{ user.campus }}</p>
    </div>

{% endblock %}

templates/user/changePassword.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau password{% endblock %}

{% block main %}

     <div classe="main">
        <h1>Changement de mot de passe</h1>


        <form method="post" action="{{ path('change_password') }}">

            <label for="password">Mot de passe actuel </label>
            <input type="password" name="_password" id="password">

            {{form_start(newPasswordForm) }}
            {{ form_widget(newPasswordForm)}}
                <button type="submit">Changer le mot de passe</button>
            {{ form_end(newPasswordForm)}}
        </form>
     </div>

{% endblock %}

templates/user/insertCSVFile.html.twig
{% extends 'base.html.twig' %}

{% block title %}Insert CSV{% endblock %}

{% block main %}

    <div class="main">

        <h1>Insert CSV</h1>
        {{form_start(csvForm) }}
        {{ form_widget(csvForm)}}
        <button type="submit">Charger le fichier</button>
        {{ form_end(csvForm)}}

    </div>

{% endblock %}

templates/user/listeUtilisateurs.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des utilisateurs{% endblock %}

{% block main %}
    <h1>Liste des utilisateurs</h1>
<div class="listSorties">

    {% for utilisateur in utilisateurs %}
        <ul class="conteneurUlList">

            <h3>{{ utilisateur.prenom }}</h3>
            <h3>{{ utilisateur.nom }}</h3>
            <p>Pseudo: {{ utilisateur.username }}</p>
            <p>Mail: {{ utilisateur.mail }}</p>
            <!--{% if utilisateur.actif == true %} -->
            <!-- <p>Actif</p> -->

                {% for role in utilisateur.roles %}
                    {% if role == 'ROLE_NOT_ACTIVATE' %}
                        <button type="submit"> <a href="{{ path('supprimer_utilisateur',{'id' : utilisateur.id }) }}">Supprimer utilisateur</a></button>
                        <button type="submit"> <a href="{{ path('debannir',{'id' : utilisateur.id }) }}">Dé-bannir</a></button>
                    {% else %}
                        <!--<button type="submit"><a href="{{ path('desactiver_utilisateur', {'id' : utilisateur.id}) }}">Désactiver l'utilisateur</a></button><br> -->
                        <button type="submit"> <a href="{{ path('supprimer_utilisateur',{'id' : utilisateur.id }) }}">Supprimer utilisateur</a></button>
                        <button type="submit"> <a href="{{ path('bannir',{'id' : utilisateur.id }) }}">Bannir</a></button>
                    {% endif%}
                {% endfor %}
            {% elseif utilisateur.actif == false %}
                <p>Non actif</p>
                <button><a href="{{ path('supprimer_utilisateur',{'id' : utilisateur.id }) }}">Supprimer utilisateur</a></button>
                        <button type="submit"> <a href="{{ path('bannir',{'id' : utilisateur.id }) }}">Bannir</a></button>
            {% endif %}



        </ul>
    {% endfor %}
</div>

{% endblock %}

templates/user/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Login{% endblock %}

{% block main %}
    <div class="main">
        <h1>Login</h1>
        <form method="post" action="{{ path('login') }}">
            <label for="username">Username : </label>
            <input type="text" name="_username" id="username">

            <label for="password">Password : </label>
            <input type="password" name="_password" id="password">

            <div class="form-group">
                <input type="checkbox" id="remember_me" name="_remember_me" checked />
                <label for="remember_me">Se souvenir de moi</label>
            </div>

            <button type="submit" class="button">Login !</button>
        </form>
        <a href="{{ path('oublie_password') }}">Vous avez oublié votre mot de passe ?!</a>
    </div>
{% endblock %}

templates/user/motDePasseOublie.html.twig
{% extends 'base.html.twig' %}

{% block title %}Oublie mot de passe{% endblock %}

{% block main %}
    <div class="main">
        <h1>Oublie mot de passe</h1>

        {{ form_start(contactForm) }}
        {{ form_widget(contactForm) }}
        {{ form_end(contactForm) }}
    </div>

{% endblock %}

templates/user/register.html.twig
{% extends 'base.html.twig' %}

{% block title %}Insertion utilisateur{% endblock %}

{% block main %}

    <div class="main">
        <h1>Insertion utilisateur </h1>

        {{ form_start(registerForm) }}
        {{ form_widget(registerForm) }}
        <button type="submit">Insérer</button>
        {{ form_end(registerForm) }}
    </div>

{% endblock %}

templates/user/resetPassword.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau mot de passe{% endblock %}

{% block main %}
    <div class="main">
        <h1>Entrez le nouveau mot de passe</h1>
        <form method="post">
            <label for="pass" >Mot de passe</label>
            <input name="password" id="pass" type="password">
            <input type="hidden" name="token" value="{{ token }}">
            <button>Valider</button>
        </form>
    </div>
{% endblock %}

templates/user/updateUser.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mise à jour utilisateur{% endblock %}


{% block main %}
    <div class="main">
        <h1>Mettez à jour votre profil</h1>
        {%  if (app.user.uRLImage)== NULL %}
        <img src="{{ asset('uploads/ProfilImage/default.png') }}" class="pdp">
        {%  else %}
        <img src="{{ asset(app.user.URLImage) }}" class="pdp">
        {% endif %}



        {{form_start(updateUserForm) }}
        {{ form_widget(updateUserForm)}}
        <button type="submit">Mettre à jour</button>
        {{ form_end(updateUserForm)}}
        <a href="{{ path('change_password', {'id': app.user.id}) }}">Mot de passe oublié ?</a>
    </div>
{% endblock %}